/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
} from './AddressDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AddressDTORequestResponse
 */
export interface AddressDTORequestResponse {
    /**
     * 
     * @type {AddressDTO}
     * @memberof AddressDTORequestResponse
     */
    response?: AddressDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AddressDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AddressDTORequestResponse interface.
 */
export function instanceOfAddressDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressDTORequestResponseFromJSON(json: any): AddressDTORequestResponse {
    return AddressDTORequestResponseFromJSONTyped(json, false);
}

export function AddressDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AddressDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AddressDTORequestResponseToJSON(value?: AddressDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AddressDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

