/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressDTOPagedResponse } from './AddressDTOPagedResponse';
import {
    AddressDTOPagedResponseFromJSON,
    AddressDTOPagedResponseFromJSONTyped,
    AddressDTOPagedResponseToJSON,
} from './AddressDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AddressDTOPagedResponseRequestResponse
 */
export interface AddressDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {AddressDTOPagedResponse}
     * @memberof AddressDTOPagedResponseRequestResponse
     */
    response?: AddressDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AddressDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AddressDTOPagedResponseRequestResponse interface.
 */
export function instanceOfAddressDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressDTOPagedResponseRequestResponseFromJSON(json: any): AddressDTOPagedResponseRequestResponse {
    return AddressDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function AddressDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AddressDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AddressDTOPagedResponseRequestResponseToJSON(value?: AddressDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AddressDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

