/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressUpdateDTO
 */
export interface AddressUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    addressField1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    addressField2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateDTO
     */
    zipCode?: string | null;
}

/**
 * Check if a given object implements the AddressUpdateDTO interface.
 */
export function instanceOfAddressUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressUpdateDTOFromJSON(json: any): AddressUpdateDTO {
    return AddressUpdateDTOFromJSONTyped(json, false);
}

export function AddressUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'addressField1': !exists(json, 'addressField1') ? undefined : json['addressField1'],
        'addressField2': !exists(json, 'addressField2') ? undefined : json['addressField2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'zipCode': !exists(json, 'zipCode') ? undefined : json['zipCode'],
    };
}

export function AddressUpdateDTOToJSON(value?: AddressUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'addressField1': value.addressField1,
        'addressField2': value.addressField2,
        'city': value.city,
        'country': value.country,
        'zipCode': value.zipCode,
    };
}

