/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressDTO } from './AddressDTO';
import {
    AddressDTOFromJSON,
    AddressDTOFromJSONTyped,
    AddressDTOToJSON,
} from './AddressDTO';

/**
 * 
 * @export
 * @interface AddressDTOPagedResponse
 */
export interface AddressDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof AddressDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<AddressDTO>}
     * @memberof AddressDTOPagedResponse
     */
    data?: Array<AddressDTO> | null;
}

/**
 * Check if a given object implements the AddressDTOPagedResponse interface.
 */
export function instanceOfAddressDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressDTOPagedResponseFromJSON(json: any): AddressDTOPagedResponse {
    return AddressDTOPagedResponseFromJSONTyped(json, false);
}

export function AddressDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(AddressDTOFromJSON)),
    };
}

export function AddressDTOPagedResponseToJSON(value?: AddressDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(AddressDTOToJSON)),
    };
}

