/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorDTO
 */
export interface AuthorDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    surname?: string | null;
}

/**
 * Check if a given object implements the AuthorDTO interface.
 */
export function instanceOfAuthorDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthorDTOFromJSON(json: any): AuthorDTO {
    return AuthorDTOFromJSONTyped(json, false);
}

export function AuthorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
    };
}

export function AuthorDTOToJSON(value?: AuthorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'surname': value.surname,
    };
}

