/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthorDTO } from './AuthorDTO';
import {
    AuthorDTOFromJSON,
    AuthorDTOFromJSONTyped,
    AuthorDTOToJSON,
} from './AuthorDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AuthorDTORequestResponse
 */
export interface AuthorDTORequestResponse {
    /**
     * 
     * @type {AuthorDTO}
     * @memberof AuthorDTORequestResponse
     */
    response?: AuthorDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AuthorDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AuthorDTORequestResponse interface.
 */
export function instanceOfAuthorDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthorDTORequestResponseFromJSON(json: any): AuthorDTORequestResponse {
    return AuthorDTORequestResponseFromJSONTyped(json, false);
}

export function AuthorDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AuthorDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AuthorDTORequestResponseToJSON(value?: AuthorDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AuthorDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

