/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorAddDTO
 */
export interface AuthorAddDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorAddDTO
     */
    surname?: string | null;
}

/**
 * Check if a given object implements the AuthorAddDTO interface.
 */
export function instanceOfAuthorAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthorAddDTOFromJSON(json: any): AuthorAddDTO {
    return AuthorAddDTOFromJSONTyped(json, false);
}

export function AuthorAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
    };
}

export function AuthorAddDTOToJSON(value?: AuthorAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'surname': value.surname,
    };
}

