/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorUpdateDTO
 */
export interface AuthorUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    surname?: string | null;
}

/**
 * Check if a given object implements the AuthorUpdateDTO interface.
 */
export function instanceOfAuthorUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthorUpdateDTOFromJSON(json: any): AuthorUpdateDTO {
    return AuthorUpdateDTOFromJSONTyped(json, false);
}

export function AuthorUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
    };
}

export function AuthorUpdateDTOToJSON(value?: AuthorUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'surname': value.surname,
    };
}

