/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookDTOPagedResponse } from './BookDTOPagedResponse';
import {
    BookDTOPagedResponseFromJSON,
    BookDTOPagedResponseFromJSONTyped,
    BookDTOPagedResponseToJSON,
} from './BookDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookDTOPagedResponseRequestResponse
 */
export interface BookDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {BookDTOPagedResponse}
     * @memberof BookDTOPagedResponseRequestResponse
     */
    response?: BookDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BookDTOPagedResponseRequestResponse interface.
 */
export function instanceOfBookDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookDTOPagedResponseRequestResponseFromJSON(json: any): BookDTOPagedResponseRequestResponse {
    return BookDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function BookDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BookDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookDTOPagedResponseRequestResponseToJSON(value?: BookDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BookDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

