/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Author } from './Author';
import {
    AuthorFromJSON,
    AuthorFromJSONTyped,
    AuthorToJSON,
} from './Author';
import type { BookGenreEnum } from './BookGenreEnum';
import {
    BookGenreEnumFromJSON,
    BookGenreEnumFromJSONTyped,
    BookGenreEnumToJSON,
} from './BookGenreEnum';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
} from './Order';
import type { Publisher } from './Publisher';
import {
    PublisherFromJSON,
    PublisherFromJSONTyped,
    PublisherToJSON,
} from './Publisher';

/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Book
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Book
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof Book
     */
    price?: number;
    /**
     * 
     * @type {Author}
     * @memberof Book
     */
    author?: Author;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    authorId?: string;
    /**
     * 
     * @type {Publisher}
     * @memberof Book
     */
    publisher?: Publisher;
    /**
     * 
     * @type {string}
     * @memberof Book
     */
    publisherId?: string;
    /**
     * 
     * @type {BookGenreEnum}
     * @memberof Book
     */
    genre?: BookGenreEnum;
    /**
     * 
     * @type {Array<Order>}
     * @memberof Book
     */
    orders?: Array<Order> | null;
}

/**
 * Check if a given object implements the Book interface.
 */
export function instanceOfBook(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookFromJSON(json: any): Book {
    return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Book {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'author': !exists(json, 'author') ? undefined : AuthorFromJSON(json['author']),
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        'publisher': !exists(json, 'publisher') ? undefined : PublisherFromJSON(json['publisher']),
        'publisherId': !exists(json, 'publisherId') ? undefined : json['publisherId'],
        'genre': !exists(json, 'genre') ? undefined : BookGenreEnumFromJSON(json['genre']),
        'orders': !exists(json, 'orders') ? undefined : (json['orders'] === null ? null : (json['orders'] as Array<any>).map(OrderFromJSON)),
    };
}

export function BookToJSON(value?: Book | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'title': value.title,
        'description': value.description,
        'year': value.year,
        'price': value.price,
        'author': AuthorToJSON(value.author),
        'authorId': value.authorId,
        'publisher': PublisherToJSON(value.publisher),
        'publisherId': value.publisherId,
        'genre': BookGenreEnumToJSON(value.genre),
        'orders': value.orders === undefined ? undefined : (value.orders === null ? null : (value.orders as Array<any>).map(OrderToJSON)),
    };
}

