/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookDTO } from './BookDTO';
import {
    BookDTOFromJSON,
    BookDTOFromJSONTyped,
    BookDTOToJSON,
} from './BookDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookDTORequestResponse
 */
export interface BookDTORequestResponse {
    /**
     * 
     * @type {BookDTO}
     * @memberof BookDTORequestResponse
     */
    response?: BookDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BookDTORequestResponse interface.
 */
export function instanceOfBookDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookDTORequestResponseFromJSON(json: any): BookDTORequestResponse {
    return BookDTORequestResponseFromJSONTyped(json, false);
}

export function BookDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : BookDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookDTORequestResponseToJSON(value?: BookDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': BookDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

