/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookGenreEnum } from './BookGenreEnum';
import {
    BookGenreEnumFromJSON,
    BookGenreEnumFromJSONTyped,
    BookGenreEnumToJSON,
} from './BookGenreEnum';

/**
 * 
 * @export
 * @interface BookAddDTO
 */
export interface BookAddDTO {
    /**
     * 
     * @type {string}
     * @memberof BookAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookAddDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BookAddDTO
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof BookAddDTO
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof BookAddDTO
     */
    authorId?: string;
    /**
     * 
     * @type {string}
     * @memberof BookAddDTO
     */
    publisherId?: string;
    /**
     * 
     * @type {BookGenreEnum}
     * @memberof BookAddDTO
     */
    genre?: BookGenreEnum;
}

/**
 * Check if a given object implements the BookAddDTO interface.
 */
export function instanceOfBookAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookAddDTOFromJSON(json: any): BookAddDTO {
    return BookAddDTOFromJSONTyped(json, false);
}

export function BookAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        'publisherId': !exists(json, 'publisherId') ? undefined : json['publisherId'],
        'genre': !exists(json, 'genre') ? undefined : BookGenreEnumFromJSON(json['genre']),
    };
}

export function BookAddDTOToJSON(value?: BookAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'year': value.year,
        'price': value.price,
        'authorId': value.authorId,
        'publisherId': value.publisherId,
        'genre': BookGenreEnumToJSON(value.genre),
    };
}

