/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BookGenreEnum = {
    Thriller: 'Thriller',
    Romance: 'Romance',
    Mystery: 'Mystery',
    Fantasy: 'Fantasy',
    Dystopian: 'Dystopian',
    Classic: 'Classic',
    Fiction: 'Fiction'
} as const;
export type BookGenreEnum = typeof BookGenreEnum[keyof typeof BookGenreEnum];


export function BookGenreEnumFromJSON(json: any): BookGenreEnum {
    return BookGenreEnumFromJSONTyped(json, false);
}

export function BookGenreEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookGenreEnum {
    return json as BookGenreEnum;
}

export function BookGenreEnumToJSON(value?: BookGenreEnum | null): any {
    return value as any;
}

