/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BookDTO } from './BookDTO';
import {
    BookDTOFromJSON,
    BookDTOFromJSONTyped,
    BookDTOToJSON,
} from './BookDTO';

/**
 * 
 * @export
 * @interface BookDTOPagedResponse
 */
export interface BookDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof BookDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof BookDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BookDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<BookDTO>}
     * @memberof BookDTOPagedResponse
     */
    data?: Array<BookDTO> | null;
}

/**
 * Check if a given object implements the BookDTOPagedResponse interface.
 */
export function instanceOfBookDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookDTOPagedResponseFromJSON(json: any): BookDTOPagedResponse {
    return BookDTOPagedResponseFromJSONTyped(json, false);
}

export function BookDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(BookDTOFromJSON)),
    };
}

export function BookDTOPagedResponseToJSON(value?: BookDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(BookDTOToJSON)),
    };
}

