/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Author } from './Author';
import {
    AuthorFromJSON,
    AuthorFromJSONTyped,
    AuthorToJSON,
} from './Author';
import type { BookGenreEnum } from './BookGenreEnum';
import {
    BookGenreEnumFromJSON,
    BookGenreEnumFromJSONTyped,
    BookGenreEnumToJSON,
} from './BookGenreEnum';
import type { Publisher } from './Publisher';
import {
    PublisherFromJSON,
    PublisherFromJSONTyped,
    PublisherToJSON,
} from './Publisher';

/**
 * 
 * @export
 * @interface BookDTO
 */
export interface BookDTO {
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BookDTO
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof BookDTO
     */
    price?: number;
    /**
     * 
     * @type {Author}
     * @memberof BookDTO
     */
    author?: Author;
    /**
     * 
     * @type {Publisher}
     * @memberof BookDTO
     */
    publisher?: Publisher;
    /**
     * 
     * @type {BookGenreEnum}
     * @memberof BookDTO
     */
    genre?: BookGenreEnum;
}

/**
 * Check if a given object implements the BookDTO interface.
 */
export function instanceOfBookDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BookDTOFromJSON(json: any): BookDTO {
    return BookDTOFromJSONTyped(json, false);
}

export function BookDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'author': !exists(json, 'author') ? undefined : AuthorFromJSON(json['author']),
        'publisher': !exists(json, 'publisher') ? undefined : PublisherFromJSON(json['publisher']),
        'genre': !exists(json, 'genre') ? undefined : BookGenreEnumFromJSON(json['genre']),
    };
}

export function BookDTOToJSON(value?: BookDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'year': value.year,
        'price': value.price,
        'author': AuthorToJSON(value.author),
        'publisher': PublisherToJSON(value.publisher),
        'genre': BookGenreEnumToJSON(value.genre),
    };
}

