/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeedbackCheckboxEnum = {
    Speed: 'Speed',
    Responsive: 'Responsive',
    Accessible: 'Accessible',
    WebPages: 'WebPages'
} as const;
export type FeedbackCheckboxEnum = typeof FeedbackCheckboxEnum[keyof typeof FeedbackCheckboxEnum];


export function FeedbackCheckboxEnumFromJSON(json: any): FeedbackCheckboxEnum {
    return FeedbackCheckboxEnumFromJSONTyped(json, false);
}

export function FeedbackCheckboxEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackCheckboxEnum {
    return json as FeedbackCheckboxEnum;
}

export function FeedbackCheckboxEnumToJSON(value?: FeedbackCheckboxEnum | null): any {
    return value as any;
}

