/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FeedbackDTO } from './FeedbackDTO';
import {
    FeedbackDTOFromJSON,
    FeedbackDTOFromJSONTyped,
    FeedbackDTOToJSON,
} from './FeedbackDTO';

/**
 * 
 * @export
 * @interface FeedbackDTORequestResponse
 */
export interface FeedbackDTORequestResponse {
    /**
     * 
     * @type {FeedbackDTO}
     * @memberof FeedbackDTORequestResponse
     */
    response?: FeedbackDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FeedbackDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FeedbackDTORequestResponse interface.
 */
export function instanceOfFeedbackDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackDTORequestResponseFromJSON(json: any): FeedbackDTORequestResponse {
    return FeedbackDTORequestResponseFromJSONTyped(json, false);
}

export function FeedbackDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FeedbackDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FeedbackDTORequestResponseToJSON(value?: FeedbackDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FeedbackDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

