/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeedbackCheckbox } from './FeedbackCheckbox';
import {
    FeedbackCheckboxFromJSON,
    FeedbackCheckboxFromJSONTyped,
    FeedbackCheckboxToJSON,
} from './FeedbackCheckbox';
import type { FeedbackSelectEnum } from './FeedbackSelectEnum';
import {
    FeedbackSelectEnumFromJSON,
    FeedbackSelectEnumFromJSONTyped,
    FeedbackSelectEnumToJSON,
} from './FeedbackSelectEnum';

/**
 * 
 * @export
 * @interface FeedbackAddDTO
 */
export interface FeedbackAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    descriere?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackAddDTO
     */
    experienta?: boolean;
    /**
     * 
     * @type {FeedbackSelectEnum}
     * @memberof FeedbackAddDTO
     */
    nota?: FeedbackSelectEnum;
    /**
     * 
     * @type {Array<FeedbackCheckbox>}
     * @memberof FeedbackAddDTO
     */
    likes?: Array<FeedbackCheckbox> | null;
}

/**
 * Check if a given object implements the FeedbackAddDTO interface.
 */
export function instanceOfFeedbackAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackAddDTOFromJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOFromJSONTyped(json, false);
}

export function FeedbackAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'descriere': !exists(json, 'descriere') ? undefined : json['descriere'],
        'experienta': !exists(json, 'experienta') ? undefined : json['experienta'],
        'nota': !exists(json, 'nota') ? undefined : FeedbackSelectEnumFromJSON(json['nota']),
        'likes': !exists(json, 'likes') ? undefined : (json['likes'] === null ? null : (json['likes'] as Array<any>).map(FeedbackCheckboxFromJSON)),
    };
}

export function FeedbackAddDTOToJSON(value?: FeedbackAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'descriere': value.descriere,
        'experienta': value.experienta,
        'nota': FeedbackSelectEnumToJSON(value.nota),
        'likes': value.likes === undefined ? undefined : (value.likes === null ? null : (value.likes as Array<any>).map(FeedbackCheckboxToJSON)),
    };
}

