/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderBook } from './OrderBook';
import {
    OrderBookFromJSON,
    OrderBookFromJSONTyped,
    OrderBookToJSON,
} from './OrderBook';

/**
 * 
 * @export
 * @interface OrderAddDTO
 */
export interface OrderAddDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderAddDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderAddDTO
     */
    addressId?: string;
    /**
     * 
     * @type {Array<OrderBook>}
     * @memberof OrderAddDTO
     */
    orderBooks?: Array<OrderBook> | null;
}

/**
 * Check if a given object implements the OrderAddDTO interface.
 */
export function instanceOfOrderAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderAddDTOFromJSON(json: any): OrderAddDTO {
    return OrderAddDTOFromJSONTyped(json, false);
}

export function OrderAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'addressId': !exists(json, 'addressId') ? undefined : json['addressId'],
        'orderBooks': !exists(json, 'orderBooks') ? undefined : (json['orderBooks'] === null ? null : (json['orderBooks'] as Array<any>).map(OrderBookFromJSON)),
    };
}

export function OrderAddDTOToJSON(value?: OrderAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'addressId': value.addressId,
        'orderBooks': value.orderBooks === undefined ? undefined : (value.orderBooks === null ? null : (value.orderBooks as Array<any>).map(OrderBookToJSON)),
    };
}

