/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderUpdateDTO
 */
export interface OrderUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateDTO
     */
    addressId?: string;
}

/**
 * Check if a given object implements the OrderUpdateDTO interface.
 */
export function instanceOfOrderUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderUpdateDTOFromJSON(json: any): OrderUpdateDTO {
    return OrderUpdateDTOFromJSONTyped(json, false);
}

export function OrderUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'addressId': !exists(json, 'addressId') ? undefined : json['addressId'],
    };
}

export function OrderUpdateDTOToJSON(value?: OrderUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'addressId': value.addressId,
    };
}

