/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderDTO } from './OrderDTO';
import {
    OrderDTOFromJSON,
    OrderDTOFromJSONTyped,
    OrderDTOToJSON,
} from './OrderDTO';

/**
 * 
 * @export
 * @interface OrderDTOPagedResponse
 */
export interface OrderDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof OrderDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<OrderDTO>}
     * @memberof OrderDTOPagedResponse
     */
    data?: Array<OrderDTO> | null;
}

/**
 * Check if a given object implements the OrderDTOPagedResponse interface.
 */
export function instanceOfOrderDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderDTOPagedResponseFromJSON(json: any): OrderDTOPagedResponse {
    return OrderDTOPagedResponseFromJSONTyped(json, false);
}

export function OrderDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(OrderDTOFromJSON)),
    };
}

export function OrderDTOPagedResponseToJSON(value?: OrderDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(OrderDTOToJSON)),
    };
}

