/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderBook
 */
export interface OrderBook {
    /**
     * 
     * @type {string}
     * @memberof OrderBook
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrderBook
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrderBook
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderBook
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderBook
     */
    bookId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderBook
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderBook interface.
 */
export function instanceOfOrderBook(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderBookFromJSON(json: any): OrderBook {
    return OrderBookFromJSONTyped(json, false);
}

export function OrderBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'orderId': !exists(json, 'orderId') ? undefined : json['orderId'],
        'bookId': !exists(json, 'bookId') ? undefined : json['bookId'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function OrderBookToJSON(value?: OrderBook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'orderId': value.orderId,
        'bookId': value.bookId,
        'quantity': value.quantity,
    };
}

