/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { PublisherDTOPagedResponse } from './PublisherDTOPagedResponse';
import {
    PublisherDTOPagedResponseFromJSON,
    PublisherDTOPagedResponseFromJSONTyped,
    PublisherDTOPagedResponseToJSON,
} from './PublisherDTOPagedResponse';

/**
 * 
 * @export
 * @interface PublisherDTOPagedResponseRequestResponse
 */
export interface PublisherDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {PublisherDTOPagedResponse}
     * @memberof PublisherDTOPagedResponseRequestResponse
     */
    response?: PublisherDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof PublisherDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the PublisherDTOPagedResponseRequestResponse interface.
 */
export function instanceOfPublisherDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublisherDTOPagedResponseRequestResponseFromJSON(json: any): PublisherDTOPagedResponseRequestResponse {
    return PublisherDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function PublisherDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublisherDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : PublisherDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function PublisherDTOPagedResponseRequestResponseToJSON(value?: PublisherDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': PublisherDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

