/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublisherDTO
 */
export interface PublisherDTO {
    /**
     * 
     * @type {string}
     * @memberof PublisherDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PublisherDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublisherDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublisherDTO
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the PublisherDTO interface.
 */
export function instanceOfPublisherDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublisherDTOFromJSON(json: any): PublisherDTO {
    return PublisherDTOFromJSONTyped(json, false);
}

export function PublisherDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublisherDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function PublisherDTOToJSON(value?: PublisherDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'address': value.address,
        'phone': value.phone,
    };
}

