/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublisherUpdateDTO
 */
export interface PublisherUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof PublisherUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PublisherUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublisherUpdateDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublisherUpdateDTO
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the PublisherUpdateDTO interface.
 */
export function instanceOfPublisherUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PublisherUpdateDTOFromJSON(json: any): PublisherUpdateDTO {
    return PublisherUpdateDTOFromJSONTyped(json, false);
}

export function PublisherUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublisherUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function PublisherUpdateDTOToJSON(value?: PublisherUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'address': value.address,
        'phone': value.phone,
    };
}

