/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserFile
 */
export interface UserFile {
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserFile
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserFile
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserFile
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof UserFile
     */
    user?: User;
}

/**
 * Check if a given object implements the UserFile interface.
 */
export function instanceOfUserFile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserFileFromJSON(json: any): UserFile {
    return UserFileFromJSONTyped(json, false);
}

export function UserFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'path': !exists(json, 'path') ? undefined : json['path'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function UserFileToJSON(value?: UserFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'path': value.path,
        'name': value.name,
        'description': value.description,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

